package consts

const (
	// json
	ERROR_CODE__JSON__UNMARSHAL_FAILED = 1105
	ERROR_CODE_CREATE_CERT_FAILED      = 2000
	ERROR_CODE_GET_CERTS_FAILED        = 2001
	ERROR_CODE_DELETE_CERT_FAILED      = 2002
	ERROR_CODE_GET_CA_CERT_FAILED      = 2003
)
